### ISSUE TITLE
Foreman reports are broken since i've installed foreman_hooks

### ISSUE THREAD

**Issue by aellert** [theforeman/foreman_hooks#10]
Hi,

Nightly cron doesn't send reports anymore since I've installed foreman_hooks.
Here is the output with --trace :

$ export RAILS_ENV=production; export FOREMAN_HOME=/usr/share/foreman; cd ${FOREMAN_HOME} && bundle exec /usr/bin/rake --trace reports:summarize
(in /usr/share/foreman)
rake aborted!
uninitialized constant Rake::DSL
/usr/share/foreman/vendor/ruby/1.8/gems/foreman_hooks-0.3.2/lib/foreman_hooks.rb:75:in `load_missing_constant'
/usr/share/foreman/Rakefile:3
/usr/lib/ruby/1.8/rake.rb:2383:in `load'
/usr/lib/ruby/1.8/rake.rb:2383:in `raw_load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2017:in `load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2016:in `load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2000:in `run'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1998:in `run'
/usr/bin/rake:28

Thanks for your help.

**Comment by mmoll** [comment]
can this get closed?
