### ISSUE TITLE
Return hook output on error

### ISSUE THREAD

**Issue by stdietrich** [theforeman/foreman_hooks#14]
This is probably an enhancement.
If a hook fails, it would be helpful to return the error output of the hook to the user.
This is mostly useful when users enter an incorrect value, which gets validated by the hook.

With #11 in place, on failure only the path is visible in the bubble.
As far as I see, the output is already captured, but it is not returned to the exception.

Regards,
Stefan

**Comment by domcleal** [comment]
This should now be fixed in 863e4cc7, since 0.3.8.
