### ISSUE TITLE
question: does foreman hooks work on Katello Content hosts too?

### ISSUE THREAD

**Issue by carlosmataguzman** [theforeman/foreman_hooks#31]
Hi! Im new to Foreman and Katello and I was wondering if I can make foreman hooks work on content hosts too, or if is there a way to add an existing host to Foreman. Ive made some research and I found a script called foreman_client but that did not work for me.

**Comment by sean797** [comment]
Yes, (since 3.0 if my memory serves be correctly) - sorry its taken so long for someone to respond.
